// generated by Fast Light User Interface Designer (fluid) version 1.0500

#ifndef tile_ex_test_h
#define tile_ex_test_h
#include <FL/Fl.H>
#include "FLE/Fle_TileEx.hpp"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
Fl_Double_Window* make_test_tileex_wnd();
#endif
