// generated by Fast Light User Interface Designer (fluid) version 1.0500

#include "tile_ex_test.h"

Fl_Double_Window* make_test_tileex_wnd() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(480, 320);
    w = o; (void)w;
    { Fle_TileEx* o = new Fle_TileEx(0, 0, 480, 320);
      o->box(FL_NO_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->align(Fl_Align(FL_ALIGN_TOP));
      o->when(FL_WHEN_RELEASE);
      { Fl_Box* o = new Fl_Box(0, 0, 114, 80);
        o->box(FL_DOWN_BOX);
        o->color(FL_LIGHT2);
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(0, 80, 114, 80);
        o->box(FL_DOWN_BOX);
        o->color(FL_LIGHT2);
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(114, 0, 66, 144);
        o->box(FL_DOWN_BOX);
        o->color(FL_LIGHT2);
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(0, 160, 114, 28);
        o->box(FL_DOWN_BOX);
        o->color(FL_LIGHT2);
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(0, 188, 75, 96);
        o->box(FL_DOWN_BOX);
        o->color(FL_LIGHT2);
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(75, 188, 39, 56);
        o->box(FL_DOWN_BOX);
        o->color(FL_LIGHT2);
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(0, 284, 480, 36);
        o->box(FL_DOWN_BOX);
        o->color(FL_LIGHT2);
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(75, 244, 200, 40);
        o->box(FL_DOWN_BOX);
        o->color((Fl_Color)11);
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(114, 204, 366, 40);
        o->box(FL_DOWN_BOX);
        o->color(FL_LIGHT2);
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(114, 144, 366, 60);
        o->box(FL_DOWN_BOX);
        o->color(FL_LIGHT2);
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(180, 112, 300, 32);
        o->box(FL_DOWN_BOX);
        o->color(FL_LIGHT2);
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(180, 0, 300, 32);
        o->box(FL_DOWN_BOX);
        o->color(FL_LIGHT2);
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(180, 32, 130, 80);
        o->box(FL_DOWN_BOX);
        o->color((Fl_Color)14);
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(310, 32, 170, 80);
        o->box(FL_DOWN_BOX);
        o->color((Fl_Color)6);
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(275, 244, 205, 40);
        o->box(FL_DOWN_BOX);
        o->color((Fl_Color)18);
      } // Fl_Box* o
      o->end();
      Fl_Group::current()->resizable(o);
      for(int i = 0; i < o->children(); i++)
      {
        Fl_Widget* w = o->child(i);
        o->size_range(w, w->w() / 2, w->h() / 2, w->w() * 2, w->h() * 2, w->w(), w->h());
      }
    } // Fle_TileEx* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}
